### ISSUE TITLE
com.fasterxml.aalto.WFCException: Illegal XML character ((CTRL-CHAR, code 128))

### ISSUE THREAD

**Issue by intracer** [FasterXML/aalto-xml#27] opened 2015-02-25 02:21 UTC
aalto-xml version 0.9.10 (0.9.9 too)

https://raw.githubusercontent.com/intracer/aalto-xml/57dcf8f75c3879ede3cbd9214aaf2c986165a153/src/test/resources/latin.xml

SJSXP, Woodstox parse ok

Exception in thread "main" com.fasterxml.aalto.WFCException: Illegal XML character ((CTRL-CHAR, code 128))
 at [row,col {unknown-source}]: [24,7]
	at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1339)
	at com.fasterxml.aalto.in.XmlScanner.handleInvalidXmlChar(XmlScanner.java:1536)
	at com.fasterxml.aalto.in.Utf8Scanner.skipCharacters(Utf8Scanner.java:806)
	at com.fasterxml.aalto.in.XmlScanner.skipToken(XmlScanner.java:425)
	at com.fasterxml.aalto.in.StreamScanner.nextFromTree(StreamScanner.java:191)
	at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:757)

**Comment by cowtowncoder** [comment] 2015-02-25 23:10
It looks like you were trying to parse Latin-1 encoded document without specifying encoding; and byte code 128 (0x80) is not valid as the first part of multi-byte character.
If so, it is not a bug but failure to specify encoding either in XML declaration (where it would allow auto-detection), via stax API (when constructing parser), or by constructing `Reader` explicitly.

However, if you did try to pass encoding information this could be a bug in Aalto. Do you have code you are using for constructing parser?

**Comment by intracer** [comment] 2015-02-26 06:01
Created a project to reproduce this bug https://github.com/intracer/aalto-issue-27
The document is UTF-8 encoded.
It does not contain 128 as a char and is successfuly parsed whith
```java
        byte[] bytes = Files.readAllBytes(Paths.get("page.xml"));
        String str = new String(bytes, Charset.forName("UTF-8")); 
        xmlInputFactory.createXMLStreamReader(new StringReader(str));
```
So maybe problem is with com.fasterxml.aalto.in.Utf8Scanner
(from stacktrace: ```at com.fasterxml.aalto.in.Utf8Scanner.skipCharacters(Utf8Scanner.java:828)```)

**Comment by cowtowncoder** [comment] 2015-02-26 06:17
Ok thank you. I will have a look and see what I can find.

**Comment by cowtowncoder** [comment] 2015-02-26 18:59
Yes, you are absolutely right. There is a bug in handling of surrogate pairs, during skipping of character data. Fix will be in 0.9.11.

**Comment by cowtowncoder** [comment] 2015-02-26 18:59
(fix itself was in second commit, not just async unit tests).

**Closed by cowtowncoder** 2015-02-26 18:59 UTC

**Comment by intracer** [comment] 2015-02-26 21:02
Thank you for fast response!
